"""Compare Bartlett, Capon, and MUSIC for two angularly separated targets.

Multiple statistically independent reflectivity snapshots are generated by
randomizing each target's initial phase. This avoids pretending that a single
rank-one snapshot can support a two-source covariance estimate.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

from pyradarsystems import (
    AngleEstimator,
    FMCWWaveform,
    PointTarget,
    RadarArray,
    RadarSystem,
    RangeDopplerProcessor,
    TDMFMCWSimulator,
    extract_virtual_snapshot,
    nearest_bin,
)
from pyradarsystems.metrics import normalize_db


def main() -> None:
    output = Path("results/two_target_resolution")
    output.mkdir(parents=True, exist_ok=True)
    waveform = FMCWWaveform(bandwidth_hz=1.5e9, chirps_per_tx=128)
    array = RadarArray.ula(
        3, 4, waveform.wavelength_m, tx_spacing_lambda=2.0, rx_spacing_lambda=0.5
    )
    system = RadarSystem(
        waveform,
        array,
        tx_power_w=0.03,
        tx_gain_linear=20,
        rx_gain_linear=20,
        receiver_noise_figure_db=6.0,
    )

    rng = np.random.default_rng(19)
    snapshots = []
    for realization in range(48):
        targets = [
            PointTarget(
                25.0,
                0.0,
                -8.0,
                rcs_sqm=20.0,
                initial_phase_rad=float(rng.uniform(0, 2 * np.pi)),
            ),
            PointTarget(
                25.0,
                0.0,
                8.0,
                rcs_sqm=20.0,
                initial_phase_rad=float(rng.uniform(0, 2 * np.pi)),
            ),
        ]
        raw = TDMFMCWSimulator(system, seed=1000 + realization).simulate(targets)
        rd = RangeDopplerProcessor(
            range_fft_size=1024, doppler_fft_size=128
        ).process(raw, waveform)
        di, ri = nearest_bin(rd, range_m=25.0, velocity_mps=0.0)
        snapshots.append(
            extract_virtual_snapshot(
                rd,
                array,
                waveform,
                frame_index=0,
                doppler_index=di,
                range_index=ri,
            )
        )

    snapshot_matrix = np.column_stack(snapshots)
    grid = np.linspace(-35, 35, 1401)
    fig, ax = plt.subplots(figsize=(8, 4.5))
    for method in ("bartlett", "capon", "music"):
        spectrum = AngleEstimator(method, diagonal_loading=1e-3).spectrum(
            snapshot_matrix,
            array.virtual_positions_m,
            waveform.wavelength_m,
            grid,
            num_sources=2,
        )
        ax.plot(grid, normalize_db(spectrum, floor_db=-50), label=method.upper())
    for angle in (-8.0, 8.0):
        ax.axvline(angle, linestyle="--", linewidth=1)
    ax.set_xlabel("Azimuth (deg)")
    ax.set_ylabel("Normalized spectrum (dB)")
    ax.set_ylim(-50, 1)
    ax.grid(True)
    ax.legend()
    ax.set_title("Two-target angular response")
    fig.tight_layout()
    fig.savefig(output / "angle_method_comparison.png", dpi=180)
    plt.close(fig)


if __name__ == "__main__":
    main()
